<img src = "https://apply.softsquared.com/custom/img/logo.png">

## 두번째 과제입니다.

우리는 파이썬 문법 2 파트에서 컨테이너 자료, 반복문, 함수 등에 대해서 배웠습니다.

이에 대한 과제를 제공해 드립니다.

과제를 하시는 동안 정보검색은 적극 권장됩니다.

## 컨테이너 자료

# Q1

num_list 라는 변수에 1~10까지의 숫자를 입력합니다.

짝수만 있는 리스트, 홀수만 있는 리스트를 각각 새로운 변수에 할당하고 호출해보세요.

In [26]:
num_list=(1,2,3,4,5,6,7,8,9,10)
oddlist=num_list[0::2]
print(oddlist)
evenlist=num_list[1::2]
print(evenlist)

(1, 3, 5, 7, 9)
(2, 4, 6, 8, 10)


In [2]:
a = []
x = 1
while x < 11:
    if x % 2 == 0:
        a.append(x)
        print(a)
    else:
        pass
    x = x+1

print(a)

[2]
[2, 4]
[2, 4, 6]
[2, 4, 6, 8]
[2, 4, 6, 8, 10]
[2, 4, 6, 8, 10]


In [20]:
a=[]
b=[]
for i in range(1,11):
    a.append(i)
print(a)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [12]:
a=[]
b=[]
c=[]
for i in range(1, 11):
          a.append(i)
          if i % 2 == 0:
                     b.append(i)
          if i % 2 == 1:
                    c.append(i)
print(a, b, c)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] [2, 4, 6, 8, 10] [1, 3, 5, 7, 9]


# Q2

주어진 두 리스트와 리스트의 연산, 추가, 삭제 등의 함수를 활용해서 다음과 같은 결과를 만들어봅시다.

```python

name1 = ["짱구", "철수", "유리", "맹구", "훈이"]
name2 = ["미선", "형만", "흰둥이", "퉁퉁이", "도라에몽"]

```

결과 : `["진구", "짱구", "철수", "맹구", "미선", "핑핑이", "흰둥이", "퉁퉁이", "도라에몽", "비실이"]`

In [31]:
name1 = ["짱구", "철수", "유리", "맹구", "훈이"]
name2 = ["미선", "형만", "흰둥이", "퉁퉁이", "도라에몽"]
total=name1+name2
print(total)               #추가 : 진구, 핑핑이, 비실이, 
                           #삭제: 유리, 훈이, 형만, 


['짱구', '철수', '유리', '맹구', '훈이', '미선', '형만', '흰둥이', '퉁퉁이', '도라에몽']


['짱구', '철수', '맹구', '미선', '흰둥이', '퉁퉁이', '도라에몽']

In [46]:
name1 = ["짱구", "철수", "유리", "맹구", "훈이"]
name2 = ["미선", "형만", "흰둥이", "퉁퉁이", "도라에몽"]
name1.remove("유리")
name1.remove("훈이")
name1.insert(0, "진구")
print(name1)

name2.remove("형만")
name2.insert(1,"핑핑이")
name2.insert(5, "비실이")
print(name2)
print(name1+name2)

['진구', '짱구', '철수', '맹구']
['미선', '핑핑이', '흰둥이', '퉁퉁이', '도라에몽', '비실이']
['진구', '짱구', '철수', '맹구', '미선', '핑핑이', '흰둥이', '퉁퉁이', '도라에몽', '비실이']


# Q3

아래 문제를 해결하세요.

1. 리스트의 합을 출력하세요.
2. 리스트의 평균을 출력하세요
3. 리스트에 저장된 데이터 개수를 출력하세요,

```python

num = [3, 4, 10, 2, 1]
```

In [172]:
num = [3, 4, 10, 2, 1]
sum(num)
def 

20

# Q4

아래의 리스트를 주어진 결과로 출력해주세요.

```python
characters = ["짱구", "철수", "유리", "맹구", "훈이"]
```

결과 : `짱구&철수&유리&맹구&훈이`

<a href="https://ourcstory.tistory.com/46"> 참고자료 </a>

In [47]:
characters = ["짱구", "철수", "유리", "맹구", "훈이"]
new = "&".join(characters)
print(new)

짱구&철수&유리&맹구&훈이


# Q5.

아래의 문자열을 주어진 결과로 출력해주세요.

```python
name = "짱구, 철수, 유리, 맹구, 훈이"
```

결과1 : `["짱구", "철수", "유리", "맹구", "훈이"]`

결과2 : `짱구&철수&유리&맹구&훈이`

In [79]:
name = "짱구, 철수, 유리, 맹구, 훈이"   # write your code here!!
list_name = name.split( )               #결과1
print(list_name)
                                          #결과2



['짱구,', '철수,', '유리,', '맹구,', '훈이']


# Q6.

다음 코드의 결과를 예측해봅니다. 그리고 그 이유를 생각해봅시다.

```python
characters = ["짱구", "철수", "유리", "맹구", "훈이"]
characters_copy = characters
characters_copy[0] = "도라에몽"
print(characters)
```

In [67]:
characters = ["짱구", "철수", "유리", "맹구", "훈이"]
characters_copy = characters
characters_copy[0] = "도라에몽"
print(characters)
#짱구가 도라에몽으로 바뀐다

['도라에몽', '철수', '유리', '맹구', '훈이']


# Q7.

로그인 어플 개발하기 문제

user_id = ['red', 'blue', 'green', 'pink']

user_pwd = ['123', 'qwe', '456', '789']

유저 아이디와 비밀번호는 각각 다음과 같이 주어져 있습니다.

사용자에게 아이디와 비밀번호를 input함수로 입력 받고,

입력받은 아이디와 비밀번호가 일치하면 '안녕하세요 ~님'을 출력하고

아이디는 일치하지만, 비밀번호는 일치하지 않는다면 '비밀번호가 틀렸습니다.'를 출력하고

아이디가 일치하지 않는다면 '존재하지 않는 아이디입니다.'를 출력하는 함수를 만들어보고, 정상작동하는지 확인해봅시다.

help)

인덱스를 찾는 내장함수, 리스트.index("요소")

어떤 요소의 존재 여부를 확인하는 방법, in, not in

In [3]:
user_id = ['red', 'blue', 'green', 'pink']

user_pwd = ['123', 'qwe', '456', '789']

In [95]:
user_id = ['red', 'blue', 'green', 'pink']
user_pwd = ['123', 'qwe', '456', '789']

input_id = input("ID입력")

if input_id in user_id:
    input_pw = input("PW입력")
if input_pw in user_pwd and user_pwd.index(input_pw) == user_id.index(input_id):
    print("로그인 성공")
else:
    print("Wrong Password")


ID입력red
PW입력55
Wrong Password


# Q8.

다음의 아이디와 비밀번호 데이터를 딕셔너리로 구성하세요.

`아이디: ['red', 'blue', 'green', 'pink']`

`비밀번호: ['123', 'qwe', '456', '789']`

In [1]:
basic_info = {"red":"123", "blue":"qwe","green":"456","pink":"789"}

In [2]:
user_id = ['red', 'blue', 'green', 'pink']

user_pwd = ['123', 'qwe', '456', '789']

user_info = {}

for i in range(len(user_id)):
    user_info[user_id[i]] = user_pwd[i]
    
user_info

{'red': '123', 'blue': 'qwe', 'green': '456', 'pink': '789'}

In [4]:
def listToDict(ID,PW):
    zipA = zip(ID,PW)
    result = dict(zipA)
    return result

ID = ['red', 'blue', 'green', 'pink']

PW = ['123', 'qwe', '456', '789']

listToDict(ID,PW)

{'red': '123', 'blue': 'qwe', 'green': '456', 'pink': '789'}

# Q9.

Q8.문제에서 만든 딕셔너리에 다음의 데이터를 추가하세요.

`아이디: "black"`

`비밀번호: "sohot"`

In [74]:
basic_info['black']='sohot'
basic_info

{'red': '123', 'blue': 'qwe', 'green': '456', 'pink': '789', 'black': 'sohot'}

# Q10.

Q8, Q9에서 만든 딕셔너리를 바탕으로 아래를 푸세요.

1. blue의 비밀번호를 "blue123"으로 변경해주세요.
2. black의 정보를 삭제해주세요.

In [76]:
basic_info={'red': '123', 'blue': 'qwe', 'green': '456', 'pink': '789', 'black': 'sohot'}
basic_info['blue']='blue123'
print(basic_info)
del basic_info["black"]
print(basic_info)

{'red': '123', 'blue': 'blue123', 'green': '456', 'pink': '789', 'black': 'sohot'}
{'red': '123', 'blue': 'blue123', 'green': '456', 'pink': '789'}


# Q11.

딕셔너리를 사용한 로그인 어플 개발하기 문제

user_info = {'red': '123', 'blue': 'blue123', 'green': '456', 'pink': '789'}

사용자 정보가 위와 같이 주어질때, 로그인 문제를 풀어보세요. 문제는 위의 `Q7.` 문제와 같습니다.

In [ ]:
user_info = {'red': '123', 'blue': 'blue123', 'green': '456', 'pink': '789'}

input_id = input("ID입력")
input_pw = input("PW입력")

if input_id in user_info:
    if user_info[input_id] == input_pw:
        print("로그인 성공")
    if user_info[input_id] != input_pw:
        print("비밀번호가 틀렸습니다.")
elif input_id not in user_info:
    print("존재하지 않는 아이디입니다.")

## 반복문(while, for)

# Q12.

1~10까지의 숫자를 입력받고, 입력 받은 숫자가 홀수인지 짝수인지 판별하는 코드를 작성해보세요.

단, 1~10까지의 숫자가 아니라면 다시 입력을 받아야합니다.

In [2]:
number = int(input("숫자를 입력하세요."))
while True :
    if 1 <= number <= 10:
        if number%2 == 1:
            print("홀수입니다.")
            break
        if number%2 == 0:
            print("짝수입니다.")
            break
    else :
        number = int(input("숫자를 재입력하세요."))
        continue

숫자를 입력하세요.11
숫자를 재입력하세요.4
짝수입니다.


# Q13.

다음과 같은 리스트가 주어졌을 때, 캐릭터의 이름과 캐릭터 글자수를 출력하세요.

```python

characters = ["섹시도발 짱구", "시크한 철수", "화난유리", "코맹맹이 맹구", "쫄보 훈이"]

```

결과예시

`섹시도발 짱구 7`

`시크한 철수 6`

~~

In [60]:
characters = ["섹시도발 짱구", "시크한 철수", "화난유리", "코맹맹이 맹구", "쫄보 훈이"]
for i in characters:
     print(i,len(i))

섹시도발 짱구 7
시크한 철수 6
화난유리 4
코맹맹이 맹구 7
쫄보 훈이 5


# Q14.

반복문을 사용해서, num에서 홀수만 출력하는 코드를 만드세요.

```pyhon
num = [1,2,3,4,5,6,7,8,9,10]
```

In [64]:
num = [1,2,3,4,5,6,7,8,9,10]
odd = []
for i in num:
    if i%2 == 1:
        odd.append(i)
odd

[1, 3, 5, 7, 9]

In [27]:
odd = [ i%2 == 1 for i in [1,2,3,4,5,6,7,8,9,10]]
odd

[True, False, True, False, True, False, True, False, True, False]

In [69]:
odd = [i for i in range(1,11) if i%2==1 ]
odd

[1, 3, 5, 7, 9]

# Q15.

반복문을 사용해서, Q14.의 num에서 `1, 2, 3을 제외하고` 출력해주세요.

In [68]:
num = [1,2,3,4,5,6,7,8,9,10]
a = []
for i in num:
    if i>3:
        a.append(i)
a

[4, 5, 6, 7, 8, 9, 10]

In [70]:
odd = [i for i in range(1,11) if i>3]
odd

[4, 5, 6, 7, 8, 9, 10]

# Q16
아래의 num 리스트를 결과와 같이 바꿔주세요.

```python
num = [12.5, 33.03, 20.78, 35.12]```

결과: `[12, 33, 20, 35]`

In [98]:
num = [12.5, 33.03, 20.78, 35.12]
결과 = []
for i in num:
    결과.append(int(i))
결과        

[12, 33, 20, 35]

In [81]:
round(13.4)

13

In [89]:
int(13.4)

13

In [94]:
num = [12.5, 33.03, 20.78, 35.12]
결과 = [ int(i) for i in num]
결과

[12, 33, 20, 35]

# Q17.

김계란씨는 회사에서 문서분류 직무를 맡고 있다. 김계란씨는 일일이 문서 확장자를 확인하며 같은 확장자끼리 분류했다. 문서분류량이 엄청난 날에는 야근하기가 일쑤였다.

이대로는 안돼겠다고 생각한 김계란씨는 최근에 소프트스퀘어드에서 프로그래밍을 배우기 시작했다.

프로그래밍을 배우고 난 뒤로부터는 매일 칼퇴근을 하고 취미생활까지 할 여유가 생겼다고 한다.

김계란씨가 평소 하는 일은 다음과 같다.

1. 김계란씨의 회사엔 `txt, py, java`  이렇게 3가지의 파일이 존재한다.
2. 김계란씨는 확장자가 같은 파일을 동일한 리스트에 보관한다.

```python
messy_files = ["wow.py", "test.txt", "haha.java", "really_final.py", "real_really_final.java", "test2.py", "whatthef.txt"]
```

햇살 좋은 어느날, 김계란씨는 직장 상사 유정란씨로부터 `messy_files`를 분류해달라는 부탁을 받았다. 김계란씨는 피식 웃으며 자신감있게 도와주겠다고 말했다.

문제 : 김계란씨의 체면이 구겨지지 않도록 `txt, py, java` 각각 확장자에 따라 text, python, java라는 변수명을 가진 리스트에 분류하는 코드를 작성해주세요.

In [115]:
messy_files = ["wow.py", "test.txt", "haha.java", "really_final.py", "real_really_final.java", "test2.py", "whatthef.txt"]
py = [file for file in messy_files if file.endswith(".py")]
txt = [file for file in messy_files if file.endswith(".txt")]
java = [file for file in messy_files if file.endswith(".java")]
print ("messy_files_py: {}".format(py))
print ("messy_files_txt: {}".format(txt))
print ("messy_files_java: {}".format(java))

messy_files_py: ['wow.py', 'really_final.py', 'test2.py']
messy_files_txt: ['test.txt', 'whatthef.txt']
messy_files_java: ['haha.java', 'real_really_final.java']


# Q18.

for문의 중첩을 활용해서

`1, 2, 3, 4`

`5, 6, 7, 8`

`9, 10, 11, 12`

`13, 14, 15, 16`

위와 같은 결과를 만들어 봅시다!

```python
# 참고
for row in range(4): # 행의 갯수와
    # 빈 리스트를 만들고
    for col in range(4): #열의 갯수만큼 반복합니다.
        # 각 요소는 row와 col과 어떤 관계가 있을까요? 
```

In [2]:
for row in range(4):
    line=[]
    for col in range(4):
        line.append(4*row +col + 1)
    print(line)

[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]
[13, 14, 15, 16]


# Q19.

사용자로부터 `1~9`정수를 입력 받습니다.
그리고 입력 받은 정수에 해당하는 구구단을 만들어봅시다.

`단, 입력값은 무조건 정수라고 가정합니다.
 단, 1~9 정수가 아니면 다시 입력을 받아야합니다.`

```python

# 실행 예시

1~9 정수를 입력하세요 : 10
1~9 정수를 입력하세요 : 20
1~9 정수를 입력하세요 : 5
5*1 = 5
5*2 = 10
~~
5*9 = 45
 

```

In [87]:
number = int(input("숫자를 입력하세요."))

while True :
    if 1 <= number <= 9:
        for j in range(1,10):
            print(f"{number}*{j} = {number*j}")
        break
    else :
        number = int(input("숫자를 재입력하세요."))
        continue

숫자를 입력하세요.77
숫자를 재입력하세요.11
숫자를 재입력하세요.2
2*1 = 2
2*2 = 4
2*3 = 6
2*4 = 8
2*5 = 10
2*6 = 12
2*7 = 14
2*8 = 16
2*9 = 18


# Q20.

김계란씨는 운동을 좋아합니다. 그의 취미는 사람들이 `N`번! 이라고 외치면 스쿼트를 `N`번 하는 것이라고 합니다.

`단, 김계란씨도 사람이기 때문에 한번에 100회 초과는 힘들다고 합니다. 즉, 1~100 사이의 정수를 입력 받아야 합니다.`

```python

# 실행 예시

스쿼트를 몇 회 할까요? -1
스쿼트를 몇 회 할까요? 200
스쿼트를 몇 회 할까요? 3
으쌰!! 스쿼트 1회
으쌰!! 스쿼트 2회
으쌰!! 스쿼트 3회
하체 운동 끝
```

In [95]:
squart = int(input("스쿼트를 몇 회 할까요?"))
while True :
    if 1<=squart<=100:
        print(f"으쌰!! 스쿼트 {squart}회")
        print("하체 운동 끝")
        break
    else :
        squart = int(input("스쿼트를 몇 회 할까요?"))

스쿼트를 몇 회 할까요?200
스쿼트를 몇 회 할까요?2
으쌰!! 스쿼트 2회
하체 운동 끝


# 함수

# Q21.

다음 조건에 맞는 함수를 작성하세요.

```함수명: y
input: x (단, x는 실수 ex, 1, 1.2, 5, 100)
output:2x+1 ```

In [108]:
def y(x):
    return 2*x + 1

In [110]:
y(1.2)

3.4

# Q22.

운동 이름과 횟수를 입력 매개변수(parameter)로 하는 함수를 만들어서 실행 해보세요. 단, 운동 횟수를 입력하지 않으면 자동으로 3회를 실행하는 함수를 만들어야합니다.

<a href ="http://studymake.blogspot.com/2015/05/default-parameter.html">참고자료</a>


`hint`
```python
# 다음과 같이 매개변수에 기본값을 지정할 수 있습니다.
def func(a="default"):
~~
```

```python

# 실행예시

exercise("팔굽혀펴기", 2)
    팔굽혀펴기를(을) 1회 실시!
    팔굽혀펴기를(을) 2회 실시!
    운동을 끝냈습니다.
    
exercise("팔굽혀펴기")
    팔굽혀펴기를(을) 1회 실시!
    팔굽혀펴기를(을) 2회 실시!
    팔굽혀펴기를(을) 3회 실시!
    운동을 끝냈습니다.
    
```

In [65]:
def exercise(팔굽혀펴기,a=3):
    for i in range(a):
        print(f"팔굽혀펴기를(을) {i+1} 회 실시!")
    print("운동을 끝냈습니다.")

In [67]:
exercise("팔굽혀펴기",7)

팔굽혀펴기를(을) 1 회 실시!
팔굽혀펴기를(을) 2 회 실시!
팔굽혀펴기를(을) 3 회 실시!
팔굽혀펴기를(을) 4 회 실시!
팔굽혀펴기를(을) 5 회 실시!
팔굽혀펴기를(을) 6 회 실시!
팔굽혀펴기를(을) 7 회 실시!
운동을 끝냈습니다.


In [61]:
a=int(input("팔굽혀펴기를 몇회할까요?"))
if a==0:
    a=3
결과 = [print(f"팔굽혀펴기를(을) {i+1} 회 실시!") for i in range(a)]
print("운동을 끝냈습니다.")

팔굽혀펴기를 몇회할까요?0
팔굽혀펴기를(을) 1 회 실시!
팔굽혀펴기를(을) 2 회 실시!
팔굽혀펴기를(을) 3 회 실시!
운동을 끝냈습니다.


In [80]:
def exersice(운동종류, 운동횟수=3):
    for i in range(운동횟수):
        print(f"{운동종류}를(을) {i+1}번 실시")
    print("운동을 끝냈습니다.")

In [85]:
exercise("팔굽혀펴기",4)

팔굽혀펴기를(을) 1 회 실시!
팔굽혀펴기를(을) 2 회 실시!
팔굽혀펴기를(을) 3 회 실시!
팔굽혀펴기를(을) 4 회 실시!
운동을 끝냈습니다.


# Q23.

정렬되지 않은 리스트를 매개변수로 전달했을 때, 정렬된 리스트가 반환되는 함수를 작성하세요.

```python

# 실행 예시

unordered = [5, 4, 2 ,10, 7, 3]
sorting(unordered)
    
    [2, 3, 4, 5, 7, 10]
```

In [226]:
def a(*args):
    new_list = []
    for i in args:
        new_list.append(i)
    return sorted(new_list)
a(5, 4, 2 ,10, 7, 3)

[2, 3, 4, 5, 7, 10]

In [229]:
lst = [ i for i in range(5)]
print(list(reversed(lst))) 
print(lst) 

[4, 3, 2, 1, 0]
[0, 1, 2, 3, 4]


In [235]:
a=(5, 4, 2 ,10, 7, 3)
print(list(reversed(a)))
b = sorted(a, reverse=True)
print(b)

[3, 7, 10, 2, 4, 5]
[10, 7, 5, 4, 3, 2]


In [238]:
a=(5, 4, 2 ,10, 7, 3)
a.sort(reverse=True)
a

AttributeError: 'tuple' object has no attribute 'sort'

# Q24.


함수에 두 개의 숫자를 전달 했을 때 사칙연산(더하기, 빼기, 곱하기, 나누기)을 수행하는 함수를 만드세요.

`(함수명, 변수명 등은 자유롭게)`

In [127]:
def y(a,b):
    return a+b, a-b, a*b, a/b

In [128]:
y(2,3)

(5, -1, 6, 0.6666666666666666)

# Q25.

다음의 조건에 맞는 함수를 작성하세요.

1. 함수명: email_classification
2. input: 이메일 주소 리스트 (ex, `[abc132@naver.com, wow880@gmail.com, hahahahaha@naver.com]`)
3. ouput: key값이 메일사이트(naver, gmail), value가 id리스트인 딕셔너리


`단, 메일 사이트는 naver와 gamail 두개 밖에 존재하지 않는다고 가정한다.`

```python

#실행예시

email_claissification(['abc132@naver.com', 'wow880@gmail.com', 'hahahahaha@naver.com'])

# 결과
{'naver':['abc123', 'hahahahahaha'], 'gmail':['wow880']}
    


```

In [41]:
import re
def  email_classification(*agrs):
    for i in agrs:
        b=','.join(i)
        print(b)
        result = re.split(r"@|,|／",b )
        print(result)

In [42]:
email_classification(['abc132@naver.com', 'wow880@gmail.com', 'hahahahaha@naver.com'])

abc132@naver.com,wow880@gmail.com,hahahahaha@naver.com
['abc132', 'naver.com', 'wow880', 'gmail.com', 'hahahahaha', 'naver.com']


In [11]:
import re

a=(['abc132@naver.com', 'wow880@gmail.com', 'hahahahaha@naver.com'])
b=",".join(a)
print(b)
result = re.split(r"@|,|／",b )

print(result)

abc132@naver.com,wow880@gmail.com,hahahahaha@naver.com
['abc132', 'naver.com', 'wow880', 'gmail.com', 'hahahahaha', 'naver.com']


In [6]:
a = ["aa@bb.c", "dd@ee.f"]
for i in a:
    split = i.split("@")
    head = split[0]
    body = split[1].split(".")[0]
    print(head)
    print(body)

aa
bb
dd
ee


In [ ]:
        a=re.split(r"@|,|／",b)
        print(a)
         b=','.join(i)

In [ ]:
input_email = input("이메일 주소를 입력하세요: ")
input_email = eval('[' + input_email + ']')
result = {'naver' : [], 'gmail':[]}

def email_classification(input_email):
    
    for i in range(len(input_email[0])):
        
        at_sign_index = input_email[0][i].find("@")
        dot_index = input_email[0][i].find(".")
        
        if input_email
    
    

In [5]:
input_email = input("이메일 주소를 입력하세요: ")
input_email = eval('[' + input_email + ']')

이메일 주소를 입력하세요: ['abc132@naver.com', 'wow880@gmail.com', 'hahahahaha@naver.com']


In [47]:
def email_classification(email):
    
    naver_id=[]
    gmail_id=[]
    
    for file in email:
        
        gmail = [file for file in email if file.endswith("@gmail.com")]
        for i in gmail:
            first = i.split("@")
            user_id = first[0]
            naver_id.append(user_id)
        print(naver_id)
        naver = [file for file in email if file.endswith("@naver.com")]
    print(gmail)
    print(naver)
        

email_classification(['abc132@naver.com', 'wow880@gmail.com', 'hahahahaha@naver.com'])

['wow880']
['wow880', 'wow880']
['wow880', 'wow880', 'wow880']
['wow880@gmail.com']
['abc132@naver.com', 'hahahahaha@naver.com']


In [32]:
email_classification = (['abc132@naver.com', 'wow880@gmail.com', 'hahahahaha@naver.com'])
gmail = [file for file in email_classification if file.endswith("@gmail.com")]
naver = [file for file in email_classification if file.endswith("@naver.com")]
print(naver)
print(gmail)

['abc132@naver.com', 'hahahahaha@naver.com']
['wow880@gmail.com']
